### ISSUE TITLE
创建新组件时，自动生成文档的位置错误。

### ISSUE THREAD

**Issue by WangJunZzz** [HeroCloudy/vue3-component-library-archetype#1]
![image](https://user-images.githubusercontent.com/25657426/201563991-ce4247b5-f705-43af-9f93-dbc63493e4eb.png)

**Comment by HeroCloudy** [comment]
谢谢反馈。前几天已重构 cli 模块，可以重新 clone 或 pull 试试。

![image](https://user-images.githubusercontent.com/99126604/202903683-8f0556d2-ba20-49c5-b944-48dd109fee0e.png)
